name: Deploy Pulumi

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Install NodeJS (required for TypeScript Pulumi project)
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Install Pulumi project dependencies
    - name: Install NPM dependencies
      run: npm install

    # Configure AWS using Access Key + Secret Key
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1

    # Login to Pulumi Cloud
    - name: Pulumi Login
      run: pulumi login

    # RUN PULUMI DEPLOY
    - name: Pulumi Deploy
      uses: pulumi/actions@v4
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      with:
        command: up
        stack-name: geethnandini47/static-website-aws-typescript/dev
